name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Java Development Kit (JDK)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Global Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.5'

    - name: Build Debug APK with Cloud Tools
      # Notice we removed the "./" and the "w". It now uses the cloud's global Gradle!
      run: gradle assembleDebug 

    - name: Upload Finished APK to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: P2-OpAIS-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk